[package]
name = "brainfuck-interpreter"
version = "1.0.0"
authors = ["Umut Şahin <umutsahin@protonmail.com>"]
edition = "2018"

[dependencies.clap]
version = "2.33.0"
features = ["suggestions", "color", "vec_map"]

[dependencies.colored]
version = "1.8.0"

[dependencies.memmap]
version = "0.7.0"
