edition = "2018"
version = "Two"
unstable_features = true

binop_separator = "Back"
blank_lines_upper_bound = 2
combine_control_expr = false
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
imports_layout = "Vertical"
match_block_trailing_comma = true
merge_imports = true
newline_style = "Unix"
normalize_doc_attributes = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
